services:
  superset:
    build: ./superset
    container_name: superset
    ports:
      - 8088:8088
    environment:
      SUPERSET_ENV: development
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      PYTHONPATH: /app/pythonpath
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
    depends_on:
      - postgres-superset
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - data_network

  postgres-superset:
    image: postgres:13
    container_name: postgres-superset
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    ports:
      - 5432:5432
    volumes:
      - ./dataset:/dataset
      - postgres_data:/var/lib/postgresql/data
      - ./database/backup:/docker-entrypoint-initdb.d             
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-superset
    networks:
      - data_network

networks:
  data_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
